### ISSUE TITLE
Should use subscribe-duration of @wasi:clocks@0.2.0/monotonic-clock instead of subscribe-frame?

### ISSUE THREAD

**Issue by Clunt** [WebAssembly/wasi-webgpu#36]
Wasm program can custom they duration in main loop?
https://github.com/WebAssembly/WASI/blob/main/wasip2/clocks/monotonic-clock.wit

**Comment by MendyBerger** [comment]
Hi @Clunt, thanks for the question.

Frame events are meant to be more than just timers, they should synchronize with the displays refresh rate. 
We have considered having a simple method to get the display's refresh rate, and have the guest use timers based on the result. No firm decision has been made yet.
If you have more thoughts on the matter, please feel free to comment. Or even better, join our weekly meeting. (I might not make today's meeting, but should be there next week)

**Comment by Clunt** [comment]
Thank you for your reply, I have some understanding of the design considerations. 
I am currently trying to encapsulate the wasi-webgpu interface in wasmi for custom program internal image drawing (2D, web pages, games, etc.). There are no specific restrictions on the rendering frame rate, which can be rendered at a frequency determined by the user's scene (power consumption, performance, etc.) combined with the display frame rate. Therefore, I may prefer the other solution you mentioned: provide the display frame rate, and let the user handle the timer and main loop. At the same time, it can be clearly divided from the existing wasi-clocks in terms of functionality.

**Comment by MendyBerger** [comment]
Sounds very interesting! Would love to have a talk if you have a few minutes! 

I'd just point out that - at least for now - you don't have to use frame events at all, you can call graphics-context.present as often as you like, frame events are completely optional.

**Comment by Clunt** [comment]
I currently use graphics-context.present in my examples, but I'm wondering if I should remove this from the web's webgpu method.

Of course, I also hope to discuss more details (MyDiscord: deer_clunt).
